version: 0.0
os: ubuntu
files:
  - source: /
    destination: /backend
hooks:
  hooks:
  BeforeInstall:
    - location: ""
      runas: ubuntu
      commands:
        - sudo apt-get update
        - sudo apt-get install python3-pip -y
        - sudo pip install gunicorn
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      runas: ubuntu
