# Azure Pipelines YAML configuration

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python3:
      PYTHON_VERSION: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    python -m pip install --upgrade pip setuptools wheel
    ls
    cd backend
    pip install -r requirements.txt

    pip install Django unittest-xml-reporting
  displayName: 'Install prerequisites'

- script: |
    ls 
    python backend/myproject/manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'backend/myproject'
    app_build_command: 'python manage.py runserver'